version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: led-hub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: led-hub-db-pass
      MYSQL_DATABASE: led-hub
      MYSQL_USER: led-hub-server
      MYSQL_PASSWORD: led-hub-db-pass
    ports:
      - '3306:3306'
    volumes:
      - led-hub-data:/var/lib/mysql
    networks:
      - led-hub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  app-server:
    build: ./hub-server
    container_name: led-hub-server
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: led-hub-server
      DB_PASSWORD: led-hub-db-pass
      DB_NAME: led-hub
      SERVER_PORT: 2000
    ports:
      - '2000:2000'  # Adjust according to your app's exposed port
    networks:
      - led-hub-network
    platform: linux/amd64

  webapp:
    build:
      context: ./hub-webapp
      args: 
        BACKEND_ROOT_URL: "http://${HOSTNAME}:2000/"
    ports:
      - '80:80'
    depends_on:
      - app-server
    networks:
      - led-hub-network

networks:
  led-hub-network:

volumes:
  led-hub-data:
