services:

  logging-service:
    build: ./logging-service
    container_name: logging-service
    restart: always
    environment:
      PORT: 8080
    ports:
      - '8080:8080' 
    networks:
      - led-hub-network
    volumes:
      - led-hub-log-data:/app/data

  server:
    build: ./server
    container_name: led-hub-server
    restart: always
    ports:
      - '${LED_HUB_BACKEND_PORT:-2000}:2000' 
    environment:
      LOGGING_SERVICE_ENDPOINT: http://logging-service:8080
      SERVER_PORT: 2000
    networks:
      - led-hub-network
    volumes:
      - led-hub-data:/app/data
    platform: linux/amd64

  webapp:
    build:
      context: ./webapp
      args: 
        BACKEND_HOST: server
        BACKEND_PORT: 2000
        LOGGER_HOST: logging-service
        LOGGER_PORT: 8080
        WEBAPP_PORT: 80
    restart: always
    ports:
      - '${LED_HUB_WEBAPP_PORT:-80}:80' 
    depends_on:
      - server
    networks:
      - led-hub-network

networks:
  led-hub-network:

volumes:
  led-hub-data:
  led-hub-log-data:
